- name: Build Image
  hosts: docker-server
  tasks:
    - name: Build Image
      command: docker build -t vishnuprasanna/docker-node-ansible .
      args:
        chdir: /home/vagrant/ansible-files
    - name: Push Image
      command: docker push vishnuprasanna/docker-node-ansible
    - name: Remove the Image Locally
      command:  docker rmi vishnuprasanna/docker-node-ansible

- name: Run Image Using Container in Docker Server
  hosts: production-server
  tasks:
    - name: Create Deployment
      command: kubectl apply -f /home/vagrant/kubernetes/deployment.yaml
    - name: Create Service
      command: kubectl apply -f /home/vagrant/kubernetes/service.yaml
      ignore_errors: yes
