apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: webapp

spec:
  replicas: 2
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: vishnuprasanna/docker-node-ansible:latest
          ports:
            - name: containerport
              containerPort: 8080
          imagePullPolicy: Always
  selector:
     matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # The maximum number of pods that can be created above the desired number of pods.
      maxUnavailable: 1  # The maximum number of pods that can be unavailable during the update process.